// Misconception library — the alternative to writing 1,400 distractor explanations.
// Wrong answers repeat. These ~40 beliefs account for the overwhelming majority of both
// MCQ distractors and wrong open-ended answers across P3-P6.
//
// Each entry: the belief, why it is wrong, and the recitation phrase that corrects it.
// Tag a wrong MCQ option, or a wrong typed answer, with an id from this list.
//
// TAG ON DEMAND, not up front. The first time a pupil picks option 3 on an item, that
// item gets tagged once and stays tagged. The corpus tags itself through use, most-
// attempted questions first, and day one requires no tagging at all.

export const MISCONCEPTIONS = [
  { id: "M-01", topic: "Heat", belief: "Cold flows into an object and makes it colder.",
    wrong: "Only heat moves. There is no such thing as a flow of cold.",
    fix: "Heat flows from a hotter region to a colder region." },
  { id: "M-02", topic: "Heat", belief: "An insulator stops heat completely.",
    wrong: "Insulators slow the rate of heat transfer; they never stop it.",
    fix: "Poor conductors do not allow heat to pass through easily." },
  { id: "M-03", topic: "Heat", belief: "Heat and temperature are the same thing.",
    wrong: "Heat is energy; temperature measures how hot or cold something is.",
    fix: "Heat is a form of energy. Temperature measures how hot or cold an object is." },
  { id: "M-04", topic: "Heat", belief: "Metals are naturally cold because they feel cold.",
    wrong: "The metal feels cold because it conducts heat away from the hand quickly.",
    fix: "Conductors allow heat to pass through easily." },
  { id: "M-05", topic: "Heat", belief: "Wrapping something in a blanket adds heat to it.",
    wrong: "A blanket only slows heat loss. It supplies no heat of its own.",
    fix: "Reduce heat loss to the surroundings by using a poor conductor of heat." },
  { id: "M-06", topic: "Heat", belief: "Objects expand because the material is added to.",
    wrong: "Mass stays the same; only the volume changes.",
    fix: "Materials expand when heated and contract when cooled. The mass remains the same." },
  { id: "M-07", topic: "Water", belief: "Water vapour is the white mist you can see.",
    wrong: "Water vapour is invisible. Visible mist is already tiny liquid droplets.",
    fix: "Water vapour loses heat and condenses into tiny water droplets." },
  { id: "M-08", topic: "Water", belief: "Water vapour touches a cold surface and turns into water.",
    wrong: "Touching is not the cause. Losing heat is the cause.",
    fix: "Water vapour loses heat to the cooler surface and condenses into water droplets." },
  { id: "M-09", topic: "Water", belief: "Evaporation only happens when water is boiling.",
    wrong: "Evaporation happens at any temperature, at the surface of the liquid.",
    fix: "Evaporation occurs at the surface at any temperature; boiling occurs throughout the liquid at its boiling point." },
  { id: "M-10", topic: "Water", belief: "Water that dries up has disappeared.",
    wrong: "It has changed state, not ceased to exist.",
    fix: "Liquid water gains heat from the surroundings and evaporates into water vapour." },
  { id: "M-11", topic: "Water", belief: "Temperature keeps rising while ice is melting.",
    wrong: "The temperature holds steady during a change of state.",
    fix: "Heat gained or lost during melting is used for the change of state, not to change the temperature." },
  { id: "M-12", topic: "Water", belief: "The droplets outside a cold glass leaked through it.",
    wrong: "They came from water vapour in the surrounding air.",
    fix: "Warm water vapour in the air loses heat to the cooler surface and condenses." },
  { id: "M-13", topic: "Matter", belief: "Gases have no mass and do not occupy space.",
    wrong: "A gas has both. It fills its container and can be compressed.",
    fix: "Matter is anything that has mass and occupies space." },
  { id: "M-14", topic: "Matter", belief: "Breaking a solid into pieces reduces the amount of matter.",
    wrong: "The shape changes; the amount of matter does not.",
    fix: "The amount of matter remains the same even though the shape changes." },
  { id: "M-15", topic: "Matter", belief: "A liquid has a fixed shape of its own.",
    wrong: "A liquid takes the shape of its container.",
    fix: "Liquids have a definite volume but no definite shape." },
  { id: "M-16", topic: "Light", belief: "We see an object because light travels from our eyes to it.",
    wrong: "Light travels from a source, is reflected by the object, and enters the eye.",
    fix: "Light from a source is reflected by the object and enters our eyes." },
  { id: "M-17", topic: "Light", belief: "A shadow is a reflection of the object.",
    wrong: "A shadow is an absence of light, not an image.",
    fix: "Light travels in a straight line. A shadow forms when an object blocks light." },
  { id: "M-18", topic: "Light", belief: "A translucent material casts no shadow.",
    wrong: "It casts a fainter shadow, because some light still passes through.",
    fix: "Translucent materials allow some light through, so the shadow is lighter." },
  { id: "M-19", topic: "Light", belief: "Moving the object closer to the screen makes its shadow bigger.",
    wrong: "It is the distance from the light source that governs the size.",
    fix: "Closer to the light source gives a bigger shadow; further gives a smaller one." },
  { id: "M-20", topic: "Plant systems", belief: "Plants take in their food from the soil.",
    wrong: "Plants make their own food in the leaves. Soil supplies water and mineral salts.",
    fix: "Leaves trap sunlight to make food for the plant. Roots absorb water and mineral salts." },
  { id: "M-21", topic: "Plant systems", belief: "Roots exist only to hold the plant up.",
    wrong: "They anchor the plant and absorb water and mineral salts.",
    fix: "Roots anchor the plant firmly and absorb water and mineral salts from the soil." },
  { id: "M-22", topic: "Plant systems", belief: "Cutting the bark stops water reaching the leaves.",
    wrong: "Removing bark removes the food-carrying tubes, not the water-carrying tubes.",
    fix: "Food cannot move downwards, so food accumulates above the cut and the lower parts lack food." },
  { id: "M-23", topic: "Plant systems", belief: "Plants breathe out oxygen instead of respiring.",
    wrong: "Plants respire like all living things; they also release oxygen during photosynthesis.",
    fix: "Oxygen is released during photosynthesis. Respiration releases energy from food." },
  { id: "M-24", topic: "Human systems", belief: "Digestion happens only in the stomach.",
    wrong: "It begins in the mouth and continues in the small intestine.",
    fix: "The mouth chews food into smaller pieces; the stomach breaks it down; the small intestine absorbs it." },
  { id: "M-25", topic: "Human systems", belief: "Food passes into the blood in the stomach.",
    wrong: "Absorption into the blood happens in the small intestine.",
    fix: "The small intestine absorbs digested food into the blood." },
  { id: "M-26", topic: "Human systems", belief: "The lungs pump blood around the body.",
    wrong: "The heart pumps blood. The lungs exchange gases.",
    fix: "The heart pumps blood through blood vessels to all parts of the body." },
  { id: "M-27", topic: "Human systems", belief: "We breathe in oxygen and breathe out only carbon dioxide.",
    wrong: "Exhaled air still contains oxygen, along with more carbon dioxide.",
    fix: "The respiratory system takes in oxygen and removes carbon dioxide." },
  { id: "M-28", topic: "Life cycles", belief: "All insects go through a pupa stage.",
    wrong: "Three-stage insects such as grasshoppers and cockroaches have no pupa.",
    fix: "A three-stage life cycle has egg, young and adult stages." },
  { id: "M-29", topic: "Life cycles", belief: "The young stage of a three-stage insect is a larva.",
    wrong: "It is a young that already resembles a smaller adult.",
    fix: "In the young stage the organism looks like a smaller adult and grows into an adult." },
  { id: "M-30", topic: "Reproduction", belief: "Pollination and fertilisation are the same event.",
    wrong: "Pollination is the transfer of pollen; fertilisation is the fusion of cells.",
    fix: "Pollination is the transfer of pollen grains from the anther to the stigma. Fertilisation is the fusion of the male reproductive cell with the egg cell." },
  { id: "M-31", topic: "Reproduction", belief: "The ovule becomes the fruit.",
    wrong: "The ovule becomes the seed; the ovary becomes the fruit.",
    fix: "The ovule develops into a seed and the ovary develops into a fruit." },
  { id: "M-32", topic: "Reproduction", belief: "Seed dispersal is about helping seeds germinate.",
    wrong: "Dispersal is about distance, which reduces competition.",
    fix: "Seed dispersal prevents overcrowding and reduces competition for light, water and space." },
  { id: "M-33", topic: "Materials", belief: "Heavy objects always sink and light ones always float.",
    wrong: "Floating does not depend on weight alone.",
    fix: "Floating materials stay on the surface of water while sinking materials go to the bottom." },
  { id: "M-34", topic: "Materials", belief: "A material can only have one useful property.",
    wrong: "Materials are chosen for a combination of properties suited to the use.",
    fix: "Choose a material with properties suitable for its function or use." },
  { id: "M-35", topic: "Magnets", belief: "All metals are attracted to magnets.",
    wrong: "Only some metals are magnetic. Aluminium and copper are not.",
    fix: "Magnets attract magnetic materials. Not all metals are magnetic." },
  { id: "M-36", topic: "Magnets", belief: "The stronger pole of a magnet attracts everything.",
    wrong: "Like poles repel regardless of strength.",
    fix: "Unlike poles attract while like poles repel." },
  { id: "M-37", topic: "Electrical system", belief: "A bulb lights if the circuit is joined anywhere.",
    wrong: "The circuit must be closed and complete.",
    fix: "A conductor allows electricity to pass through to form a closed circuit." },
  { id: "M-38", topic: "Forces", belief: "A moving object stops because it runs out of force.",
    wrong: "It stops because friction opposes its motion.",
    fix: "Frictional force opposes motion and gradually reduces the object's kinetic energy until it stops." },
  { id: "M-39", topic: "Forces", belief: "Weight and mass are the same thing.",
    wrong: "Weight is the gravitational force acting on a mass.",
    fix: "Weight is the gravitational force acting on an object." },
  { id: "M-40", topic: "Environment", belief: "Removing a predator always helps the prey population.",
    wrong: "The prey population may then overgrow and exhaust its food supply.",
    fix: "Competition for food, water and space decreases population size." },
  { id: "M-41", topic: "Environment", belief: "Decomposers are harmful because they cause rot.",
    wrong: "Decomposition returns nutrients to the soil.",
    fix: "Decomposers return mineral salts and nutrients to the soil for plant growth." },
  { id: "M-42", topic: "Answer technique", belief: "Naming the correct science fact is enough to earn the mark.",
    wrong: "The fact must be joined to the set-up described in the question.",
    fix: "State the concept, then link it to the evidence in the question to reach your answer." },
  { id: "M-43", topic: "Heat", belief: "When a ring and a ball no longer fit, it must be the ball that changed.",
    wrong: "Whichever object gained heat is the one that expanded. Pupils attribute the change to the wrong object.",
    fix: "Materials expand when heated and contract when cooled. Identify which object gained or lost the heat.",
    observedIn: "MOE 2025 Monograph, story C9" },
  { id: "M-44", topic: "Matter", belief: "Two objects of the same volume must have the same mass.",
    wrong: "Volume and mass are separate properties.",
    fix: "Matter is anything that has mass and occupies space. Same space occupied does not mean same mass.",
    observedIn: "MOE 2025 Monograph, story C5" },
  { id: "M-45", topic: "Light", belief: "Your eyes adjust in a dark room, so eventually you can see an object.",
    wrong: "With no light at all there is nothing to reflect into the eye.",
    fix: "Light from a source is reflected by the object and enters our eyes. Without light we cannot see.",
    observedIn: "MOE 2025 Monograph, story C8" },
  { id: "M-46", topic: "Plant systems", belief: "A cactus is not really a plant because it has no proper leaves.",
    wrong: "Classification rests on characteristics of living things, not on resembling a typical plant.",
    fix: "Plants make their own food. Leaves trap sunlight to make food — a cactus's spines are its leaves.",
    observedIn: "MOE 2025 Monograph, story C7" },
];

export const BY_TOPIC = MISCONCEPTIONS.reduce((m, x) => {
  (m[x.topic] = m[x.topic] || []).push(x.id); return m;
}, {});

// M-42 is not a science misconception but an answering habit, and it is the single most
// common cause of lost marks in this corpus. It is what CECL's Link exists to fix.
export const TECHNIQUE_IDS = ["M-42"];

export const STATS = { count: MISCONCEPTIONS.length, topics: Object.keys(BY_TOPIC).length };
