// Science knowledge base — the base definition of science content for marking.
// Source: user's Google Drive "P3/P4/P5/P6 SCIENCE" folders.
//   AL1 RECITATION TABLES  → question : fixed recitation answer (the model answer)
//   WA1 TRIGGER BANKS      → question clue : keywords needed to explain
// Pedagogy: OEQ answers follow fixed explanations. Marking = did the pupil produce
// the required keywords, in the required causal order — not "is it broadly right".
//
// Item shape: { q, a, k } — q question, a recitation answer, k required keyword phrases.

export const RECITATION = [
  { level: "P3", chapter: 1, title: "Living and Non-Living Things", syllabus: "Diversity of Living and Non-Living Things (P3)", items: [
    { q: "What are the characteristics of living things?", a: "Living things grow, reproduce, respond to changes and need air, water and food.", k: ["grow", "reproduce", "respond to changes", "need air, water and food"] },
    { q: "What are non-living things?", a: "Non-living things do not grow, reproduce or respond to changes.", k: ["do not grow", "do not reproduce", "do not respond"] },
    { q: "What do living things need to survive?", a: "Living things need air, water and food.", k: ["air", "water", "food"] },
    { q: "Why did the animal / insect / fish die in the container or tank?", a: "It did not have air or food to survive.", k: ["did not have air", "did not have food"] },
    { q: "Why must containers have holes?", a: "To allow air in for breathing.", k: ["allow air in", "for breathing"] },
    { q: "What is one difference between plants and animals?", a: "Plants make their own food, animals cannot.", k: ["plants make their own food", "animals cannot"] },
    { q: "Why is the animal classified as a bird?", a: "Birds have feathers and lay eggs.", k: ["feathers", "lay eggs"] },
    { q: "Why is the animal classified as a mammal?", a: "Mammals have hair or fur and feed their young with milk.", k: ["hair or fur", "feed young with milk"] },
    { q: "Why is the animal classified as a fish?", a: "Fish have gills, fins and scales and breathe through gills.", k: ["gills", "fins", "scales"] },
    { q: "Why is the animal classified as an insect?", a: "Insects have three body parts, six legs and one pair of antennae.", k: ["three body parts", "six legs", "one pair of antennae"] },
    { q: "What group do mushrooms belong to and how do they reproduce?", a: "Mushrooms are fungi and reproduce by spores.", k: ["fungi", "spores"] },
    { q: "Why does fungus grow faster in warm wet places?", a: "Fungi grow well in warm and moist conditions.", k: ["warm", "moist"] },
    { q: "What are the main parts of a plant and their functions?", a: "Roots absorb water, stem supports the plant, leaves make food, flowers form fruit.", k: ["roots absorb water", "stem supports", "leaves make food", "flowers form fruit"] },
    { q: "How do water plants help fish survive?", a: "Water plants produce oxygen for fish to breathe.", k: ["produce oxygen", "for fish to breathe"] },
  ]},
  { level: "P3", chapter: 2, title: "Materials", syllabus: "Diversity of Materials (P3)", items: [
    { q: "What are materials?", a: "Materials are substances used to make objects.", k: ["substances", "used to make objects"] },
    { q: "Why are different materials used for different objects?", a: "Different materials have different properties suitable for different uses.", k: ["different properties", "suitable for different uses"] },
    { q: "What is a property of a material?", a: "A property describes how a material behaves or what it is like.", k: ["how a material behaves"] },
    { q: "What are common properties of materials?", a: "Common properties include strength, flexibility, transparency, waterproofness, absorbency and ability to float or sink.", k: ["strength", "flexibility", "transparency", "waterproof", "absorbency", "float or sink"] },
    { q: "What does strong mean and why must some objects be strong?", a: "Strong materials can support heavy weight and do not break easily.", k: ["support heavy weight", "do not break easily"] },
    { q: "What does flexible mean and why must some objects be flexible?", a: "Flexible materials can bend easily without breaking.", k: ["bend easily", "without breaking"] },
    { q: "What does transparent mean and why are transparent materials used?", a: "Transparent materials allow light to pass through so objects can be seen through them.", k: ["allow light to pass through", "can be seen through"] },
    { q: "What does opaque mean?", a: "Opaque materials do not allow light to pass through.", k: ["do not allow light to pass through"] },
    { q: "What does waterproof mean and why are waterproof materials used?", a: "Waterproof materials do not allow water to pass through.", k: ["do not allow water to pass through"] },
    { q: "What does absorbent mean?", a: "Absorbent materials soak up water easily.", k: ["soak up water"] },
    { q: "What does it mean when a material floats or sinks?", a: "Floating materials stay on the surface of water, while sinking materials go to the bottom.", k: ["stay on the surface", "go to the bottom"] },
    { q: "How do we choose a suitable material for an object?", a: "Choose a material with properties suitable for its function or use.", k: ["properties suitable for its use"] },
    { q: "How do we conduct a fair test when comparing materials?", a: "Keep all variables the same except the one being tested.", k: ["keep all variables the same", "except the one being tested"] },
    { q: "What variables must be kept the same in material experiments?", a: "Variables such as size, thickness or length of the materials must be kept the same.", k: ["size", "thickness", "length"] },
    { q: "How do we conclude which material is most suitable?", a: "The most suitable material has the required property for the object's use.", k: ["required property", "for the object's use"] },
  ]},
  { level: "P3", chapter: 3, title: "Life Cycles", syllabus: "Cycles in Plants and Animals (Life Cycles) (P3)", items: [
    { q: "What is a life cycle?", a: "A life cycle is the series of stages a living thing goes through from egg or birth to adult and reproduction.", k: ["series of stages", "to adult", "reproduction"] },
    { q: "What is a 4-stage life cycle?", a: "A 4-stage life cycle has egg → larva → pupa → adult stages.", k: ["egg", "larva", "pupa", "adult"] },
    { q: "Which animals have a 4-stage life cycle?", a: "Animals such as butterflies, mosquitoes, beetles and houseflies have a 4-stage life cycle.", k: ["butterfly", "mosquito", "beetle", "housefly"] },
    { q: "What happens in the larva stage?", a: "In the larva stage, the organism feeds and grows quickly.", k: ["feeds", "grows quickly"] },
    { q: "What happens in the pupa stage?", a: "In the pupa stage, the organism changes into an adult.", k: ["changes into an adult"] },
    { q: "What happens in the adult stage?", a: "In the adult stage, the organism reproduces and lays eggs.", k: ["reproduces", "lays eggs"] },
    { q: "What is a 3-stage life cycle?", a: "A 3-stage life cycle has egg → young → adult stages.", k: ["egg", "young", "adult"] },
    { q: "Which animals have a 3-stage life cycle?", a: "Animals such as frogs, grasshoppers and cockroaches have a 3-stage life cycle.", k: ["frog", "grasshopper", "cockroach"] },
    { q: "What happens in the young stage?", a: "In the young stage, the organism looks like a smaller adult and grows into an adult.", k: ["looks like a smaller adult", "grows into an adult"] },
    { q: "What is one similarity between animal life cycles?", a: "A similarity is that both life cycles have an egg stage.", k: ["both have an egg stage"] },
    { q: "What is one difference between animal life cycles?", a: "A difference is that one life cycle has three stages while another has four stages.", k: ["three stages", "four stages"] },
    { q: "Why do some animals lay many eggs?", a: "Animals lay many eggs so that some will survive even if others are eaten by predators.", k: ["some will survive", "eaten by predators"] },
    { q: "How does temperature affect the mosquito life cycle?", a: "Higher temperatures cause mosquitoes to grow faster, so the life cycle becomes shorter.", k: ["grow faster", "life cycle shorter"] },
    { q: "What are the stages of a plant life cycle?", a: "The stages of a plant life cycle are seed → young plant → adult plant → seeds produced.", k: ["seed", "young plant", "adult plant", "seeds produced"] },
    { q: "What happens when plants grow too close together?", a: "Plants growing too close together compete for light, water and space.", k: ["compete", "light, water and space"] },
  ]},
  { level: "P4", chapter: 1, title: "Plant Systems", syllabus: "Plant System (Plant parts and functions) (P4)", items: [
    { q: "What is the function of roots?", a: "Roots anchor the plant firmly in the ground and absorb water and mineral salts from the soil.", k: ["anchor the plant", "absorb water and mineral salts"] },
    { q: "What is the function of the stem?", a: "The stem supports the plant and transports water and food to all parts of the plant.", k: ["supports the plant", "transports water and food"] },
    { q: "What is the function of leaves?", a: "Leaves trap sunlight to make food for the plant.", k: ["trap sunlight", "make food"] },
    { q: "How do leaves make food?", a: "Chlorophyll in leaves traps sunlight to make food during photosynthesis.", k: ["chlorophyll", "traps sunlight", "photosynthesis"] },
    { q: "What are stomata?", a: "Stomata are tiny openings on leaves that allow gases to be exchanged between the plant and the surroundings.", k: ["tiny openings on leaves", "gases exchanged"] },
    { q: "What gases are exchanged through stomata?", a: "Carbon dioxide enters and oxygen exits the leaf.", k: ["carbon dioxide enters", "oxygen exits"] },
    { q: "Why do stomata open wider during photosynthesis?", a: "To allow more gaseous exchange.", k: ["more gaseous exchange"] },
    { q: "Why are more bubbles seen on the underside of leaves in water plants?", a: "There are more stomata on the underside of leaves.", k: ["more stomata on the underside"] },
    { q: "What gas is released during photosynthesis?", a: "Oxygen.", k: ["oxygen"] },
    { q: "What are the two transport tubes in plants?", a: "Water-carrying tubes transport water from the roots to the rest of the plant, while food-carrying tubes transport food from the leaves to the rest of the plant.", k: ["water-carrying tubes", "from the roots", "food-carrying tubes", "from the leaves"] },
    { q: "How does water move in a plant?", a: "Water moves from the roots to the stem and then to the leaves and fruits.", k: ["roots", "stem", "leaves"] },
    { q: "What happens if water-carrying tubes are removed?", a: "Water cannot reach the upper parts of the plant so the parts above the cut will die.", k: ["water cannot reach upper parts", "parts above the cut die"] },
    { q: "What happens if food-carrying tubes are removed?", a: "Food cannot move downwards so food accumulates above the cut and the lower parts lack food.", k: ["food cannot move downwards", "accumulates above the cut", "lower parts lack food"] },
    { q: "Why does the stem swell above a ring-removed bark?", a: "Food accumulates above the cut because the food-carrying tubes were removed.", k: ["food accumulates above the cut", "food-carrying tubes removed"] },
    { q: "Why do fruits above the removed bark grow bigger?", a: "More food accumulates above the cut.", k: ["more food accumulates above the cut"] },
    { q: "Why will a plant eventually die after bark removal?", a: "Food cannot reach the roots so the roots die and cannot absorb water.", k: ["food cannot reach the roots", "roots die", "cannot absorb water"] },
    { q: "Why does a plant wilt when water transport is blocked?", a: "The leaves do not receive enough water.", k: ["leaves do not receive enough water"] },
    { q: "Why do plants bend towards sunlight?", a: "Plants grow towards sunlight to obtain light for making food.", k: ["grow towards sunlight", "for making food"] },
    { q: "What conditions are needed for photosynthesis?", a: "Light and carbon dioxide are needed for photosynthesis.", k: ["light", "carbon dioxide"] },
    { q: "Where can plants store food?", a: "Plants may store food in roots, stems or leaves.", k: ["roots", "stems", "leaves"] },
  ]},
  { level: "P4", chapter: 2, title: "Human Systems", syllabus: "Human System (Digestive System) (P4)", items: [
    { q: "What are the three human body systems studied?", a: "The three human body systems are the digestive, circulatory and respiratory systems.", k: ["digestive", "circulatory", "respiratory"] },
    { q: "How do the digestive, circulatory and respiratory systems work together?", a: "The digestive system absorbs digested food into the blood, the circulatory system transports digested food and oxygen to cells, and the respiratory system supplies oxygen for respiration.", k: ["absorbs digested food into the blood", "transports to cells", "supplies oxygen for respiration"] },
    { q: "What is the function of the digestive system?", a: "The digestive system breaks down food into simpler substances and absorbs digested food into the blood.", k: ["breaks down food into simpler substances", "absorbs digested food into the blood"] },
    { q: "What is the function of the mouth in digestion?", a: "The mouth chews food into smaller pieces.", k: ["chews food into smaller pieces"] },
    { q: "Why does chewing food help digestion?", a: "Chewing breaks food into smaller pieces and increases surface area for digestive juices to act faster.", k: ["smaller pieces", "increases surface area", "digestive juices act faster"] },
    { q: "What is the function of the gullet?", a: "The gullet passes food from the mouth to the stomach and digestion does not occur there.", k: ["passes food to the stomach", "no digestion"] },
    { q: "What is the function of the stomach?", a: "The stomach breaks down food into simpler substances using digestive juices.", k: ["breaks down food", "digestive juices"] },
    { q: "What is the function of the small intestine?", a: "The small intestine absorbs digested food into the blood.", k: ["absorbs digested food into the blood"] },
    { q: "What is the function of the large intestine?", a: "The large intestine absorbs water from undigested food.", k: ["absorbs water", "undigested food"] },
    { q: "What are the three parts of the circulatory system?", a: "The circulatory system consists of the heart, blood and blood vessels.", k: ["heart", "blood", "blood vessels"] },
    { q: "What is the function of the circulatory system?", a: "The circulatory system transports digested food and oxygen to cells and carries carbon dioxide away from cells.", k: ["transports digested food and oxygen", "carries carbon dioxide away"] },
    { q: "What is the function of the heart?", a: "The heart pumps blood through blood vessels to all parts of the body.", k: ["pumps blood", "to all parts of the body"] },
    { q: "What is the function of blood vessels?", a: "Blood vessels transport blood throughout the body.", k: ["transport blood"] },
    { q: "What is the function of the respiratory system?", a: "The respiratory system takes in oxygen and removes carbon dioxide.", k: ["takes in oxygen", "removes carbon dioxide"] },
    { q: "Why do cells need oxygen?", a: "Cells use oxygen for respiration to release energy from food.", k: ["respiration", "release energy from food"] },
    { q: "Why does limewater turn chalky when we blow into it?", a: "Limewater turns chalky because exhaled air contains carbon dioxide.", k: ["exhaled air", "contains carbon dioxide"] },
  ]},
  { level: "P4", chapter: 3, title: "Matter", syllabus: "Cycles in Matter and Water (Matter) (P4)", items: [
    { q: "What is matter?", a: "Matter is anything that has mass and occupies space.", k: ["has mass", "occupies space"] },
    { q: "What are the three states of matter?", a: "The three states of matter are solid, liquid and gas.", k: ["solid", "liquid", "gas"] },
    { q: "What are the properties of solids?", a: "Solids have a definite shape and a definite volume.", k: ["definite shape", "definite volume"] },
    { q: "What are the properties of liquids?", a: "Liquids have a definite volume but no definite shape and take the shape of the container.", k: ["definite volume", "no definite shape", "take the shape of the container"] },
    { q: "What are the properties of gases?", a: "Gases have no definite shape, no definite volume and can be compressed.", k: ["no definite shape", "no definite volume", "can be compressed"] },
    { q: "Why can air be pumped into a container already filled with air?", a: "Air can be compressed and occupies space.", k: ["can be compressed", "occupies space"] },
    { q: "Why does a balloon change shape when pressed?", a: "The air inside the balloon can be compressed.", k: ["air can be compressed"] },
    { q: "Why does water level rise when an object is placed in water?", a: "The object occupies space and displaces water.", k: ["occupies space", "displaces water"] },
    { q: "Why will water overflow when another object is added into a full container?", a: "The added object occupies space and displaces more water.", k: ["occupies space", "displaces more water"] },
    { q: "How can we measure the volume of an irregular solid?", a: "Submerge the solid in water and measure the volume of water displaced.", k: ["submerge in water", "volume of water displaced"] },
    { q: "Why does the total volume remain the same after breaking a solid into smaller pieces?", a: "The amount of matter remains the same even though the shape changes.", k: ["amount of matter remains the same", "shape changes"] },
    { q: "Why does melted chocolate appear to occupy less space than chocolate cubes?", a: "Air spaces between cubes are removed when the chocolate melts.", k: ["air spaces removed"] },
    { q: "Why must butter be melted before pouring into a mould?", a: "Liquid butter has no definite shape and takes the shape of the mould.", k: ["no definite shape", "takes the shape of the mould"] },
    { q: "Why can cubes be separated from water using a filter funnel?", a: "The solid cubes are trapped while the liquid water flows through.", k: ["solid trapped", "liquid flows through"] },
    { q: "What happens to the mass of an object when it is heated?", a: "The mass remains the same when heated.", k: ["mass remains the same"] },
    { q: "Why does hot water cool after the flame is removed?", a: "The water loses heat to the cooler surroundings.", k: ["loses heat", "cooler surroundings"] },
    { q: "Why can a container appear full but still hold more water?", a: "Air spaces between solids allow water to occupy the spaces.", k: ["air spaces", "water occupies the spaces"] },
  ]},
  { level: "P4", chapter: 4, title: "Heat Energy", syllabus: "Energy Forms and Uses (Heat) (P4)", items: [
    { q: "What is heat?", a: "Heat is a form of energy.", k: ["form of energy"] },
    { q: "What is temperature?", a: "Temperature measures how hot or cold an object is.", k: ["measures how hot or cold"] },
    { q: "In which direction does heat flow?", a: "Heat flows from a hotter region to a colder region.", k: ["from hotter", "to colder"] },
    { q: "What happens when an object gains heat?", a: "The object's temperature increases.", k: ["temperature increases"] },
    { q: "What happens when an object loses heat?", a: "The object's temperature decreases.", k: ["temperature decreases"] },
    { q: "Why does hot tea cool when left on a table?", a: "The tea loses heat to the cooler surroundings.", k: ["loses heat", "cooler surroundings"] },
    { q: "Why does a metal spoon become hot in hot water?", a: "The spoon gains heat from the hot water.", k: ["gains heat", "from the hot water"] },
    { q: "What are conductors and insulators of heat?", a: "Conductors allow heat to pass through easily, while insulators do not allow heat to pass through easily.", k: ["conductors allow heat through easily", "insulators do not"] },
    { q: "Why are metal pots used for cooking but plastic or wooden handles used on pots?", a: "Metal conducts heat well so food cooks faster, while plastic or wood are poor conductors that reduce heat transfer to the hand.", k: ["metal conducts heat well", "cooks faster", "poor conductors", "reduce heat transfer to the hand"] },
    { q: "Why does a cardboard sleeve reduce the heat felt on a cup?", a: "Cardboard is a poor conductor of heat and reduces heat transfer to the hand.", k: ["poor conductor", "reduces heat transfer to the hand"] },
    { q: "What happens to materials when they gain or lose heat?", a: "Materials expand when heated and contract when cooled.", k: ["expand when heated", "contract when cooled"] },
    { q: "Why are gaps left between railway tracks?", a: "The metal gains heat and expands, so gaps allow expansion.", k: ["gains heat", "expands", "gaps allow expansion"] },
    { q: "How can heat loss be reduced so food cooks faster or stays warm longer?", a: "Reduce heat loss to the surroundings by covering the container with a lid or using a poor conductor of heat.", k: ["reduce heat loss to the surroundings", "lid or poor conductor"] },
  ]},
  { level: "P4", chapter: 5, title: "Light Energy & Shadow", syllabus: "Energy Forms and Uses (Light) (P4)", items: [
    { q: "What is light energy? What are sources of light?", a: "Light is a form of energy. A source of light gives out light — Sun, lamp, torch, fire, candle flame.", k: ["form of energy", "gives out light"] },
    { q: "How do we see objects?", a: "Light from a source is reflected by the object and enters our eyes. Pattern: source → object → reflected light → eye.", k: ["light from a source", "reflected by the object", "enters our eyes"] },
    { q: "Why can't we see an object in a dark box or dark place unless there is light?", a: "We need light to see. Without light, no reflected light enters the eye.", k: ["no reflected light", "enters the eye"] },
    { q: "How is a shadow formed? What property of light causes it?", a: "Light travels in a straight line. A shadow forms when an object blocks light.", k: ["travels in a straight line", "object blocks light"] },
    { q: "What are transparent, translucent and opaque materials?", a: "Transparent allows most light through and can be seen through clearly; translucent allows some light through and the image is blurred; opaque allows no light through and blocks light.", k: ["most light", "some light", "no light"] },
    { q: "Why is glass or a goggle lens used when we need to see through clearly?", a: "Choose a transparent material because it allows most light to pass through and lets us see clearly.", k: ["transparent", "allows most light through"] },
    { q: "Why are blackout curtains used for privacy?", a: "Choose the material that allows the least or no light to pass through — opaque is best.", k: ["no light passes through", "opaque"] },
    { q: "What property must a puppet-show screen have?", a: "The screen should allow some light to pass through — a translucent screen so the audience can view the shadow.", k: ["some light passes through", "translucent"] },
    { q: "What material makes the darkest shadow?", a: "Use an opaque material because it blocks light completely and gives the darkest shadow.", k: ["opaque", "blocks light completely"] },
    { q: "How do light sensors or dataloggers count objects, or compare how much light passes through?", a: "When an object passes by it blocks the light, so the reading drops; count the dips to count objects. If the reading does not go to zero, some light still passes through.", k: ["blocks the light", "reading drops", "does not go to zero means some light passes"] },
    { q: "How does distance affect the size of a shadow?", a: "Closer to the light source gives a bigger shadow; further from the light source gives a smaller shadow.", k: ["closer gives bigger shadow", "further gives smaller shadow"] },
    { q: "Why conduct a light experiment in a dark room?", a: "To ensure only the light from the source affects the results, with no external light interference.", k: ["only light from the source", "no external light"] },
    { q: "What must be kept the same in a fair test for light or shadow experiments?", a: "Keep light intensity, distance between light source and screen, and size or thickness of materials constant. Change one variable only.", k: ["light intensity", "distance", "size or thickness", "change one variable only"] },
    { q: "How can experiment results be made more reliable?", a: "Repeat the experiment several times and take the average.", k: ["repeat", "take the average"] },
    { q: "Why are shiny or reflective surfaces easily seen at night?", a: "Shiny or reflective surfaces reflect more light into our eyes.", k: ["reflect more light", "into our eyes"] },
    { q: "Trap to memorise", a: "If an object does not block the light path, the shadow will not change.", k: ["no blocking of light path", "no shadow change"] },
  ]},
  { level: "P5", chapter: 1, title: "Plant and Human Reproduction", syllabus: "Cycles in Plants and Animals (Reproduction) (P5)", items: [
    { q: "Why do plants reproduce?", a: "Plants reproduce to continue their species.", k: ["continue their species"] },
    { q: "What are the main reproductive parts of a flower?", a: "Anther, stigma, ovary and filament.", k: ["anther", "stigma", "ovary", "filament"] },
    { q: "What is pollination?", a: "Pollination is the transfer of pollen grains from the anther to the stigma.", k: ["transfer of pollen grains", "anther to the stigma"] },
    { q: "How do insects help pollination?", a: "Insects carry pollen grains from the anther of one flower to the stigma of another flower.", k: ["carry pollen grains", "anther of one flower", "stigma of another"] },
    { q: "What is fertilisation in plants?", a: "Fertilisation occurs when the male reproductive cell from pollen fuses with the egg cell in the ovule.", k: ["male reproductive cell", "fuses with the egg cell", "in the ovule"] },
    { q: "What happens to the ovule after fertilisation?", a: "The ovule develops into a seed.", k: ["ovule develops into a seed"] },
    { q: "What happens to the ovary after fertilisation?", a: "The ovary develops into a fruit.", k: ["ovary develops into a fruit"] },
    { q: "Why did a flower not develop into a fruit?", a: "Fertilisation did not occur.", k: ["fertilisation did not occur"] },
    { q: "What are the stages of reproduction in flowering plants?", a: "Pollination → fertilisation → seed dispersal → germination.", k: ["pollination", "fertilisation", "seed dispersal", "germination"] },
    { q: "What is seed dispersal?", a: "Seed dispersal is the scattering of seeds away from the parent plant.", k: ["scattering of seeds", "away from the parent plant"] },
    { q: "Why is seed dispersal important?", a: "It prevents overcrowding and reduces competition for light, water and space.", k: ["prevents overcrowding", "reduces competition", "light, water and space"] },
    { q: "How are seeds dispersed by wind?", a: "Seeds are light and small and can be carried by wind.", k: ["light and small", "carried by wind"] },
    { q: "How are seeds dispersed by animals?", a: "Animals eat fruits and pass out the seeds in their droppings away from the parent plant.", k: ["eat fruits", "pass out seeds in droppings"] },
    { q: "How are seeds dispersed by water?", a: "Fruits float and are carried away by water currents.", k: ["float", "carried by water"] },
    { q: "How are seeds dispersed by splitting?", a: "The fruit splits open suddenly and flings the seeds away.", k: ["splits open suddenly", "flings the seeds"] },
    { q: "What feature allows seeds to stick to animals?", a: "Hooks or stiff hairs that attach to animal fur.", k: ["hooks", "stiff hairs", "attach to fur"] },
    { q: "Why can seeds dispersed by animals survive digestion?", a: "Seeds have tough seed coats that protect them.", k: ["tough seed coats"] },
    { q: "What reproductive cells are produced in humans?", a: "Sperm cells in males and egg cells in females.", k: ["sperm cells", "egg cells"] },
    { q: "Which organ produces sperms?", a: "The testes produce sperms.", k: ["testes"] },
    { q: "Which organ produces eggs?", a: "The ovaries produce eggs.", k: ["ovaries"] },
    { q: "What is fertilisation in humans?", a: "Fertilisation occurs when a sperm cell fuses with an egg cell.", k: ["sperm cell fuses with an egg cell"] },
    { q: "Where does fertilisation occur in humans?", a: "Fertilisation occurs in the fallopian tube (oviduct).", k: ["fallopian tube"] },
    { q: "Where does the baby develop in the human body?", a: "The baby develops in the uterus.", k: ["uterus"] },
    { q: "What is heredity?", a: "Heredity is the passing of traits from parents to offspring.", k: ["passing of traits", "parents to offspring"] },
  ]},
  { level: "P5", chapter: 5, title: "Water and the Three States", syllabus: "Cycles in Matter and Water (Water) (P5)", items: [
    { q: "What are the three states of water?", a: "Water exists as solid (ice), liquid (water) and gas (water vapour).", k: ["solid ice", "liquid water", "gas water vapour"] },
    { q: "What are the properties of solids, liquids and gases?", a: "Solid: definite shape and volume. Liquid: definite volume but no fixed shape. Gas: no definite shape and no definite volume.", k: ["definite shape and volume", "definite volume no fixed shape", "no definite shape or volume"] },
    { q: "What happens when water gains heat?", a: "Water gains heat and changes state: ice melts to water, and water evaporates or boils to form water vapour.", k: ["gains heat", "melts", "evaporates or boils"] },
    { q: "What happens when water loses heat?", a: "Water loses heat and changes state: water vapour condenses to water, and water freezes to ice.", k: ["loses heat", "condenses", "freezes"] },
    { q: "What is melting?", a: "Melting is the change of state from solid to liquid when heat is gained.", k: ["solid to liquid", "heat gained"] },
    { q: "What is freezing?", a: "Freezing is the change of state from liquid to solid when heat is lost.", k: ["liquid to solid", "heat lost"] },
    { q: "What is evaporation?", a: "Evaporation is the change of liquid water to water vapour at the surface when heat is gained.", k: ["liquid to water vapour", "at the surface", "heat gained"] },
    { q: "What is condensation?", a: "Condensation is the change of water vapour to liquid water when heat is lost.", k: ["water vapour to liquid", "heat lost"] },
    { q: "What is boiling?", a: "Boiling is the change of liquid water to water vapour throughout the liquid when heated to its boiling point.", k: ["throughout the liquid", "at its boiling point"] },
    { q: "Why do water droplets form on cold surfaces such as cups, mirrors or windows?", a: "Water vapour in the air loses heat to the cooler surface and condenses into water droplets.", k: ["water vapour", "loses heat to the cooler surface", "condenses"] },
    { q: "Why do wet clothes dry faster in wind or higher temperature?", a: "Higher temperature or wind increases the rate of evaporation.", k: ["increases the rate of evaporation"] },
    { q: "Why do people feel cold when water evaporates from their skin?", a: "Evaporation removes heat from the skin, causing cooling.", k: ["removes heat from the skin", "cooling"] },
    { q: "How does temperature affect evaporation?", a: "Higher temperature increases the rate of evaporation.", k: ["higher temperature", "faster evaporation"] },
    { q: "How does surface area affect evaporation?", a: "Larger exposed surface area increases the rate of evaporation.", k: ["larger exposed surface area", "faster evaporation"] },
    { q: "Why does water vapour appear as mist or fog in cold air?", a: "Water vapour loses heat in cold air and condenses into tiny water droplets forming mist.", k: ["loses heat", "condenses into tiny droplets"] },
    { q: "Why does salt cause ice to melt faster?", a: "Salt lowers the melting point of ice, causing ice to melt faster.", k: ["lowers the melting point"] },
    { q: "Why is salt spread on icy roads?", a: "Salt lowers the melting point of ice so ice melts and roads become less slippery.", k: ["lowers the melting point", "less slippery"] },
  ]},
  { level: "P6", chapter: 1, title: "Energy in Food", syllabus: "Energy Forms and Uses (Photosynthesis) (P6)", items: [
    { q: "Why do living things need energy?", a: "Energy is needed for life processes: growth, movement and respiration." },
    { q: "Where does the energy in food originate from?", a: "Energy in food originates from the Sun." },
    { q: "How do plants obtain energy and make food?", a: "Plants use light energy from the Sun during photosynthesis to make food." },
    { q: "What is photosynthesis?", a: "Carbon dioxide + water → food (glucose) + oxygen, using light energy." },
    { q: "Why are plants producers?", a: "Plants make their own food by photosynthesis." },
    { q: "Why are animals consumers?", a: "Animals obtain energy by eating plants or other animals." },
    { q: "How is energy released from food?", a: "Respiration: food is broken down using oxygen to release energy." },
    { q: "What is respiration?", a: "Food (glucose) + oxygen → carbon dioxide + water + energy." },
    { q: "How are photosynthesis and respiration related?", a: "Photosynthesis produces food and oxygen; respiration produces carbon dioxide used in photosynthesis." },
    { q: "Why does respiration increase during exercise?", a: "More energy is needed for muscle movement." },
    { q: "What is a food chain?", a: "A food chain shows energy transfer from one organism to another." },
    { q: "Why is energy lost in food chains?", a: "Energy is used for life processes and lost as heat." },
    { q: "Why are fewer organisms found at higher trophic levels?", a: "Less energy is available at each level of the food chain." },
  ]},
  { level: "P6", chapter: 2, title: "Eight Forms of Energy", syllabus: "Energy Conversion (P6 Standard)", items: [
    { q: "What is energy?", a: "Energy is the ability to do work or cause change." },
    { q: "What are the eight forms of energy?", a: "Heat, light, sound, electrical, kinetic, chemical potential, elastic potential and gravitational potential." },
    { q: "What happens to energy in a system?", a: "Energy cannot be created or destroyed but can be converted from one form to another." },
    { q: "What is kinetic energy?", a: "Kinetic energy is the energy of a moving object." },
    { q: "What factors affect kinetic energy?", a: "Kinetic energy increases with greater mass and greater speed." },
    { q: "What happens to kinetic energy when an object slows down?", a: "Kinetic energy is converted to heat and sound due to friction." },
    { q: "What is gravitational potential energy?", a: "Gravitational potential energy is stored energy due to height above the ground." },
    { q: "What factors affect gravitational potential energy?", a: "It increases with greater mass and greater height." },
    { q: "What happens to gravitational potential energy when an object falls?", a: "It converts to kinetic energy as the object moves downward." },
    { q: "What is elastic potential energy?", a: "Stored energy in stretched or compressed objects such as springs or rubber bands." },
    { q: "What factors affect elastic potential energy?", a: "It increases when the object is stretched or compressed more." },
    { q: "What is chemical potential energy?", a: "Stored energy in substances such as food, fuel and batteries." },
    { q: "How is chemical potential energy used by living things?", a: "Chemical potential energy in food is converted to kinetic and heat energy during movement and activities." },
    { q: "What is electrical energy?", a: "Energy carried by moving electric charges in a circuit." },
    { q: "What is light energy?", a: "Energy that allows objects to be seen." },
    { q: "What is heat energy?", a: "Energy transferred from a hotter object to a cooler object." },
    { q: "What is sound energy?", a: "Energy produced by vibrating objects." },
    { q: "What energy conversion occurs in a torch or battery-powered device?", a: "Chemical potential energy converts to electrical energy, then to light and heat energy." },
  ]},
  { level: "P6", chapter: 3, title: "Forces", syllabus: "Interaction of Forces (P6)", items: [
    { q: "What is a force?", a: "A force is a push or pull acting on an object." },
    { q: "What are the effects of force?", a: "A force can start or stop motion, change speed, change direction, or change shape." },
    { q: "What is frictional force?", a: "Frictional force is a force between two surfaces in contact that opposes motion." },
    { q: "What factors affect frictional force?", a: "Friction increases with rougher surfaces and greater mass of the object." },
    { q: "How can friction be reduced?", a: "By using lubricants, wheels or ball bearings, and smoother surfaces." },
    { q: "What is elastic spring force?", a: "A force exerted by a stretched or compressed spring or elastic object." },
    { q: "What happens when a spring is stretched or compressed?", a: "Elastic spring force acts to return the spring to its original length." },
    { q: "What is the relationship between load and spring extension?", a: "Greater load causes greater extension or compression of the spring." },
    { q: "What is magnetic force?", a: "A force of attraction or repulsion between magnets or magnetic materials." },
    { q: "How do magnetic poles interact?", a: "Unlike poles attract while like poles repel." },
    { q: "What is gravitational force?", a: "The force of attraction between objects with mass." },
    { q: "What is weight?", a: "Weight is the gravitational force acting on an object." },
    { q: "What forces act on an object moving down a slope?", a: "Gravitational force pulls the object down the slope while frictional force opposes the motion." },
    { q: "What forces act on a hanging or stationary object?", a: "Gravitational force acts downward while elastic or support force acts upward." },
    { q: "Why does an object eventually stop moving on a surface?", a: "Frictional force opposes motion and gradually reduces the object's kinetic energy until it stops." },
    { q: "Why does a heavier object require more force to move?", a: "A heavier object has greater gravitational force acting on it, increasing friction with the surface." },
    { q: "Why do objects slide further on smoother surfaces?", a: "Smoother surfaces produce less friction so less energy is lost and the object moves further." },
    { q: "What forces act on objects falling through air?", a: "Gravitational force pulls the object downward while air resistance opposes the motion." },
  ]},
  { level: "P6", chapter: 4, title: "Living Together", syllabus: "Interactions within the Environment (P6)", items: [
    { q: "What is a habitat?", a: "A habitat is the natural environment where an organism lives." },
    { q: "What conditions must a habitat provide?", a: "A habitat provides air, water, food, space and shelter." },
    { q: "What is a population?", a: "All organisms of the same species living in a habitat." },
    { q: "What is a community?", a: "Different populations living together in the same habitat." },
    { q: "What is interdependence?", a: "Interdependence means organisms depend on one another for survival." },
    { q: "What are living and non-living factors affecting survival?", a: "Living: predators, prey, competitors. Non-living: light, water, temperature, air." },
    { q: "What is a predator?", a: "An organism that hunts and eats other organisms." },
    { q: "What is prey?", a: "An organism that is hunted and eaten by a predator." },
    { q: "How does prey population affect predator population?", a: "More prey increases predator population; less prey decreases predator population." },
    { q: "How does predator population affect prey population?", a: "More predators decrease prey population; fewer predators increase prey population." },
    { q: "How does competition affect populations?", a: "Competition for food, water, space or light decreases population size." },
    { q: "Why do producers affect populations in a habitat?", a: "Producers make food by photosynthesis and provide energy for consumers." },
    { q: "Why are fish found in areas with plants and light?", a: "Plants photosynthesise and produce oxygen for fish respiration." },
    { q: "What is decomposition?", a: "The breakdown of dead organisms into simpler substances." },
    { q: "Why are decomposers important?", a: "Decomposers return mineral salts and nutrients to the soil for plant growth." },
    { q: "How does pollution affect organisms in a habitat?", a: "Pollution reduces suitable living conditions and decreases population size." },
  ]},
  { level: "P6", chapter: 6, title: "People and Environment", syllabus: "Interactions within the Environment (P6)", items: [
    { q: "What is pollution?", a: "Pollution is the release of harmful substances into the environment." },
    { q: "What are the main types of pollution?", a: "Air, water and land pollution harm living things and the environment." },
    { q: "How does burning fossil fuels cause global warming?", a: "Burning fossil fuels releases carbon dioxide which traps heat, causing global warming." },
    { q: "How does deforestation cause global warming?", a: "Cutting trees reduces carbon dioxide absorption, increasing carbon dioxide that traps heat." },
    { q: "How does deforestation affect organisms?", a: "Habitat is destroyed so organisms lose shelter and food, causing population decrease." },
    { q: "How does deforestation cause soil erosion?", a: "Without roots holding soil, soil is easily washed away by rain." },
    { q: "How does soil erosion affect plants in water?", a: "Soil blocks light so there is less light for photosynthesis, reducing plant growth." },
    { q: "How does pollution cause death of aquatic organisms?", a: "Pollutants reduce oxygen or block photosynthesis, causing organisms to die." },
    { q: "How does global warming affect sea levels?", a: "Global warming melts ice caps, causing sea level rise and flooding." },
    { q: "How does global warming increase disease spread?", a: "Higher temperature causes organisms to reproduce faster, so more disease carriers are present." },
    { q: "How does haze form?", a: "Burning forests releases smoke and particles, causing haze." },
    { q: "How does wind affect pollution levels?", a: "Wind carries pollutants to other areas, increasing pollution levels." },
    { q: "How do trees prevent soil erosion and landslides?", a: "Roots hold soil together, preventing it from being washed away." },
    { q: "How do renewable energy sources benefit the environment?", a: "Renewable energy reduces pollution and does not run out." },
    { q: "How does wastewater treatment help the environment?", a: "It removes pollutants before water is released, reducing pollution." },
  ]},
];

// Trigger bank — maps what the question LOOKS like to the keywords required.
// This is the recognition step: before marking, identify which recitation answer applies.
export const TRIGGERS = [
  { level: "P5", topic: "Water Cycle", trigger: "Water droplets / foggy mirror / mist / fog / clouds form", keywords: "Warmer water vapour from ( ) loses heat to cooler air or cooler surface on ( ) and condenses into water droplets." },
  { level: "P5", topic: "Water Cycle", trigger: "No water droplets or fog on heated mirror / warm surface", keywords: "The surface is not cool enough for warm water vapour to lose heat and condense, so little or no water droplets form." },
  { level: "P5", topic: "Water Cycle", trigger: "Wet clothes dry / water droplets disappear / water level decreases", keywords: "Liquid water gains heat from the surroundings and evaporates into water vapour." },
  { level: "P5", topic: "Water Cycle", trigger: "Clothes dry faster in wind / higher temperature / larger exposed surface area", keywords: "Wind, higher temperature or larger exposed surface area increases the rate of evaporation." },
  { level: "P5", topic: "Water Cycle", trigger: "Clothes dry slower / evaporation reduced by oil or covering", keywords: "Oil or covering prevents water from escaping into the air, so evaporation is reduced or prevented." },
  { level: "P5", topic: "Water Cycle", trigger: "Person feels cold when sweat or water evaporates from skin", keywords: "Water gains heat from the skin and evaporates; heat is removed from the skin, causing cooling." },
  { level: "P5", topic: "Water Cycle", trigger: "Rain forms / rain falls from clouds", keywords: "Tiny water droplets in clouds join together, become larger and heavier, then fall as rain." },
  { level: "P5", topic: "Water Cycle", trigger: "Sea / pond / river water becomes water vapour", keywords: "Water gains heat from the Sun and evaporates into water vapour." },
  { level: "P5", topic: "Water Cycle", trigger: "Water collected from sea water using bottle / solar still", keywords: "Sea water gains heat and evaporates into water vapour. The vapour touches a cooler surface, loses heat and condenses into water droplets. The droplets flow down and are collected." },
  { level: "P5", topic: "Water Cycle", trigger: "More drinking water collected in one set-up than another", keywords: "The water has a larger exposed surface area, so evaporation is faster and more water vapour condenses into water droplets." },
  { level: "P5", topic: "Water Cycle", trigger: "Less drinking water collected when cap / cover is removed", keywords: "Water vapour escapes into the surroundings, so less water vapour is available to condense." },
  { level: "P5", topic: "Water Cycle", trigger: "Plants in closed jar / terrarium get continuous water supply", keywords: "Water evaporates from moist soil, condenses on the cooler inner surface of the jar, then falls back to the soil as water droplets." },
  { level: "P5", topic: "Water Cycle", trigger: "Ice melts / butter changes to oil", keywords: "The solid gains heat and changes state from solid to liquid. This process is melting." },
  { level: "P5", topic: "Water Cycle", trigger: "Water freezes / warm coffee becomes frozen", keywords: "The liquid loses heat and changes state from liquid to solid. This process is freezing." },
  { level: "P5", topic: "Water Cycle", trigger: "Evaporation vs boiling", keywords: "Evaporation occurs at the surface of the liquid and can happen at any temperature. Boiling occurs throughout the liquid at its boiling point." },
  { level: "P5", topic: "Water Cycle", trigger: "Temperature stays the same during melting or freezing", keywords: "Heat gained or lost is used for the change of state, not to change the temperature." },
  { level: "P5", topic: "Water Cycle", trigger: "Ice melts faster in hotter water or more water", keywords: "The ice gains more heat from the hotter or larger amount of water, so it melts faster." },
  { level: "P5", topic: "Water Cycle", trigger: "Identify state using melting point and boiling point", keywords: "Below melting point: solid. Between melting and boiling point: liquid. Above boiling point: gas." },
  { level: "P5", topic: "Water Cycle", trigger: "Identify liquid parts in a water cycle diagram", keywords: "Sea, rain and water droplets in clouds are liquid water. Water vapour is gas." },
  { level: "P5", topic: "Plant Reproduction", trigger: "Flower develops into fruit after fertilisation", keywords: "Fertilisation has occurred. The ovary develops into the fruit and the ovule develops into the seed." },
  { level: "P5", topic: "Plant Reproduction", trigger: "Flower does not develop into fruit", keywords: "Fertilisation did not occur." },
  { level: "P5", topic: "Plant Reproduction", trigger: "Seed dispersed by wind", keywords: "Seeds are light and small, or have wing-like or hair-like structures, so they can be carried by wind." },
  { level: "P5", topic: "Plant Reproduction", trigger: "Seed dispersed by water", keywords: "Fruits have fibrous husks or air spaces that allow them to float and be carried away by water." },
  { level: "P5", topic: "Plant Reproduction", trigger: "Seed does not germinate in freezer", keywords: "The temperature is too low; the seed does not have enough warmth to germinate." },
  { level: "P5", topic: "Plant Reproduction", trigger: "Anther compared to human testes", keywords: "The anther produces pollen grains, which contain male reproductive cells." },
  { level: "P5", topic: "Human Reproduction", trigger: "Fallopian tube is cut or blocked", keywords: "The sperm cell may not meet the egg cell, so fertilisation may not occur." },
  { level: "P5", topic: "Human Reproduction", trigger: "Sperms can still enter female body even if fallopian tube is blocked", keywords: "Sperms enter the female body through the vagina." },
  { level: "P5", topic: "Human Reproduction", trigger: "Uterus is damaged or removed", keywords: "The fertilised egg cannot develop properly because the uterus is where the baby develops." },
  { level: "P5", topic: "Human Reproduction", trigger: "Baby receives useful substances from mother", keywords: "Oxygen and digested food pass from the mother's blood to the baby's blood." },
  { level: "P5", topic: "Human Reproduction", trigger: "Baby removes waste substances", keywords: "Carbon dioxide and waste substances pass from the baby's blood to the mother's blood." },
  { level: "P5", topic: "Human Reproduction", trigger: "Child looks like parents but not exactly the same", keywords: "The child inherits traits from both parents, so the combination of traits may be different." },
];

// Two trigger banks are image-only PDFs (P4 WA1, P6 WA1) — their diagrams and
// question images need OCR / manual entry before they can be indexed here.
export const PENDING_SOURCES = [
  "P4 Science WA1 Trigger Bank (Plant Systems, Human Systems, Matter, Light and Shadow) — 77 MB, image-based",
  "P6 Science WA1 Trigger Bank (Energy from Food, Types of Energy, Forces, Living Together) — 60 MB, image-based",
];

export const STATS = {
  chapters: RECITATION.length,
  items: RECITATION.reduce((n, c) => n + c.items.length, 0),
  triggers: TRIGGERS.length,
};
